variable "root_cidrs" {
  description = "Top-level CIDR blocks available for allocation (e.g., [\"10.0.0.0/8\"])"
  type        = list(string)
}

variable "reserved_cidrs" {
  description = "CIDRs already in use. Generated by scripts/discover-ip-allocations.sh. New allocations will not overlap with these."
  type        = list(string)
  default     = []
}

variable "allocations" {
  description = "IP address allocation plan. Defines environments, VNets, and subnets with their CIDR sizes."
  type = map(object({
    # Environment-level allocation
    cidr_newbits = number  # bits to add to root CIDR for this environment (e.g., 8 gives /16 from a /8)
    cidr_index   = number  # index within the root CIDR (0, 1, 2, ...)
    vnets = map(object({
      cidr_newbits = number  # bits to add to environment CIDR for this VNet
      cidr_index   = number  # index within the environment CIDR
      subnets = map(object({
        cidr_newbits = number  # bits to add to VNet CIDR for this subnet
        cidr_index   = number  # index within the VNet CIDR
      }))
    }))
  }))
  default = {}
}
