variable "resource_group_name" {
  type = string
}

variable "location" {
  type = string
}

variable "environment" {
  type = string
}

# IPAM allocation plan — the single source of truth for all IP addresses
variable "ipam_root_cidrs" {
  type    = list(string)
  default = ["10.0.0.0/8"]
}

variable "ipam_reserved_cidrs" {
  description = "Generated by scripts/discover-ip-allocations.sh"
  type        = list(string)
  default     = []
}

variable "ipam_allocation" {
  description = "IPAM allocation for this environment"
  type = object({
    cidr_newbits = number
    cidr_index   = number
    vnets = map(object({
      cidr_newbits = number
      cidr_index   = number
      subnets = map(object({
        cidr_newbits = number
        cidr_index   = number
      }))
    }))
  })
}

# Optional overrides — callers only set what they need
variable "nsg_rules" {
  description = "NSG rules per subnet. Key matches subnet name from IPAM allocation."
  type = map(map(object({
    priority                   = number
    direction                  = string
    access                     = string
    protocol                   = string
    source_port_range          = optional(string, "*")
    destination_port_range     = optional(string, null)
    destination_port_ranges    = optional(list(string), null)
    source_address_prefix      = optional(string, null)
    destination_address_prefix = optional(string, null)
    description                = optional(string, null)
  })))
  default = {}
}

variable "route_tables" {
  description = "Route table definitions. Key matches VNet name from IPAM allocation."
  type = map(object({
    bgp_route_propagation_enabled = optional(bool, true)
    routes = map(object({
      address_prefix         = string
      next_hop_type          = string
      next_hop_in_ip_address = optional(string, null)
    }))
    subnet_keys = optional(list(string), [])
  }))
  default = {}
}

variable "tags" {
  type    = map(string)
  default = {}
}
